services:
  fastapi_app:
    image: dfanaro/ugo-backend-data:latest
    container_name: fastapi_app
    command: "./runner.sh"
    ports:
      - "8081:8081"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8081
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - APP=api
      - PORT=8081
    networks:
      - app_network

  streamlit_app:
    image: dfanaro/ugo-backend-data:latest
    container_name: streamlit_app
    command: "./runner.sh"
    ports:
      - "8082:8082"
    environment:
      - STREAMLIT_SERVER_PORT=8082
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_URL=${API_URL}
      - APP=web
      - PORT=8082
    depends_on:
      - fastapi_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
