version: '3.8'

services:
  fastapi_app:
    image: ugo-backend-data-api:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    networks:
      - app_network

  streamlit_app:
    image: ugo-backend-data-web:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    depends_on:
      - fastapi_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
